ItauProjeto/Controllers/CadastrarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ItauProjeto.CRUD;
using ItauProjeto.Funcoes;
using ItauProjeto.Models;

namespace ItauProjeto.Controllers
{
    public class CadastrarController : Controller
    {
        private CRUDCliente crud;
        private ModelCliente model;
        private ConfigUpload configUpload;

        public CadastrarController()
        {
            crud = new CRUDCliente();
            model = new ModelCliente();
        }

        public ActionResult Index(string id)
        {
            return View(model);            
        }

        [HttpPost]
        public ActionResult Index(ModelCliente model)
        {
            if (ModelState.IsValid)
            {
                //primeiro eu insiro o cliente na base, depois salvo o ComprovanteEndereco na pasta do ID gerado para este cliente
                model.NomeDoArquivo = model.ComprovanteEndereco.FileName;
                string idGerado = crud.Salvar(model).ToString();

                if (idGerado != "0")
                {
                    //salvar comprovante
                    if (Diretorio.criarPasta("//upload//", idGerado))
                    {
                        //como estou usando um classe que desenvolvi para fazer recortes de imagem e criar miniaturas preciso criar essas pastas
                        if (Diretorio.criarPasta("//upload//" + idGerado + "//", "crop") && Diretorio.criarPasta("//upload//" + idGerado + "//", "min"))
                        {
                            configUpload = new ConfigUpload(idGerado, "arquivo", 0, 0, "", Request.PhysicalApplicationPath);
                            configUpload.SalvarArquivo(model.ComprovanteEndereco);
                        }
                    }

                    return RedirectToAction("Index", new { id = idGerado });
                }
            }
            return View(model);
        }
    }
}

ItauProjeto/Controllers/CompartilhadoController.cs
using ItauProjeto.CRUD;
using ItauProjeto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ItauProjeto.Controllers
{
    public class CompartilhadoController : Controller
    {

        [ChildActionOnly]
        public ActionResult GetSessionLogin()
        {
            ViewModelCompartilhado modelSession = new ViewModelCompartilhado();
            HttpCookie cookie = Request.Cookies["loggedCliente"];
            if (cookie != null)
            {
                 Session["loggedCliente"] = cookie.Value;
            }
            if (Session["loggedCliente"] != null)
            {
                CRUDCliente crud = new CRUDCliente();
                modelSession.login = crud.ListarPorID(Session["loggedCliente"].ToString())?.Nome;
                modelSession.id = Session["loggedCliente"].ToString();
            }

            if (cookie != null && string.IsNullOrEmpty(modelSession.login))
            {
                Response.Cookies["loggedCliente"].Expires = DateTime.Now.AddDays(-1);
                Session["loggedCliente"] = null;
            }
            return PartialView("~/Views/Shared/_GetSessionLogin.cshtml", modelSession);
        }

        [ChildActionOnly]
        public ActionResult LayoutMessage()
        {
            return PartialView("~/Views/Shared/_LayoutMessage.cshtml");
        }

        [ChildActionOnly]
        public ActionResult LayoutFormExclusao(string id)
        {
            CRUDCliente crud = new CRUDCliente();
            ModelCliente model = crud.ListarPorID(id);
            return PartialView("~/Views/Shared/_LayoutFormExclusao.cshtml", model);
        }

        public ActionResult Fechar()
        {
            Session["loggedCliente"] = null;
            Response.Cookies["loggedCliente"].Expires = DateTime.Now.AddDays(-1);
            return RedirectToAction("Index", "Home");
        }

    }
}

ItauProjeto/Views/Shared/_GetSessionLogin.cshtml
@model ItauProjeto.Models.ViewModelCompartilhado

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index", "Home")"><img src="~/Content/images/logo-itau.png" /></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li><a href="@Url.Action("Index", "Cadastrar")">Cadastrar cliente</a></li>
                @{
                    if (!string.IsNullOrEmpty(Model.login))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" stlye="color:#fff;">Gerenciar perfil<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Editar", "Portal", new { id = Model.id })">Editar perfil</a></li>
                                <li><a href="@Url.Action("AlterarSenha", "Portal", new { id = Model.id })">Alterar senha</a></li>
                                <li role="separator" class="divider"></li>
                                @*<li class="dropdown-header">Nav header</li>*@
                                @*<li><a onclick="excluirConta(@Model.id,'@(Url.Action("JsonAjaxExcluir", "Portal"))');" class="pointer">Excluir perfil</a></li>*@
                                <li><a onclick="excluindoCliente();" class="pointer">Excluir perfil</a></li>
                            </ul>
                        </li>
                        <li><a style="color:#fff;">Cliente: @Model.login</a></li>
                        <li class="active"><a href="@Url.Action("Fechar", "Compartilhado")">Sair</a></li>
                    }
                }
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

ItauProjeto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/logo-itau.png" rel="shortcut icon" type="image/x-icon" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/ajxandjs")

</head>
<body>
    @Html.Action("LayoutMessage", "Compartilhado")
    @Html.Action("GetSessionLogin", "Compartilhado")
    
    @RenderBody()

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ItauProjeto/Views/Shared/_LayoutMessage.cshtml
<div id="excluindo" class="excluindoFixed">
    <p>
        Atenção!
    </p>
    <div class="text">
    </div>
    <div class="centro">
        <div id="btnConfirmOk" class="btn btn-success fRightButton">Confirmar</div>
        <div id="btnConfirmCancel" class="btn btn-danger fRightButton" style="float:left;">Cancelar</div>
    </div>
</div>
<div id="excluindoAlert" class="excluindo excluindoFixed">
    <p>
        Atenção
    </p>
    <div class="text">
    </div>
    <div class="centro">
        <div id="btnConfirmAlert" class="btn btn-success center">OK</div>
    </div>
</div>